### Spring properties

# HTTP Server (Tomcat) Port
server:
  port: 9191
  address: localhost    
  
# Discovery Server Access
#eureka:
#    client:
#      register-with-eureka: true
#      fetch-registry: true
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka/
     

     
    
     
    