spring:
  application:
    name: security-service

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost

server:
  port: 9898
  address: localhost
