eureka:
  client:
    register-with-eureka: false
server:
  port: 9191
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: booksearch
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/students/**
        - id: bookstore
          uri: http://localhost:5000
          predicates:
            - Path=/api/v1/schools/**