
server:
  port: 2345

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/ramachandranmrr/spring-app-config
          uri: https://github.com/ramachandranmrr/microservices-jlc
          default-label: cloud-server-demo
          search-paths: config-repo

          skipSslValidation: false
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
