
spring:
  application:
    name: booksearch
  config:
    import: optional:configserver:http://localhost:2345


# any name ok but after - (-dev or -mydev)
# booksearch-dev.properties (Dev Profile)
# spring.profiles.active=dev

# booksearch-qa.properties (Qa Profile)
# spring.profiles.active=qa

